name       : gnome-recipes
version    : 1.4.6
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-recipes/1.4/gnome-recipes-1.4.6.tar.xz : 792585df5cb77ee670ca9eb8e6b0fceb823fe092805c026466f01d153f3e9833
license    : GPL-3.0
component  : desktop.gnome
summary    : An easy-to-use application that will help you to discover what to cook today, tomorrow, the rest of the week and for your special occasions.
description: |
    An easy-to-use application that will help you to discover what to cook today, tomorrow, the rest of the week and for your special occasions.
builddeps  :
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gspell-1)
    - pkgconfig(libcanberra)
    - pkgconfig(libsoup-2.4)
    - git
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/gnome-dbus-issue.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
