name       : gnome-recipes
version    : 1.6.2
release    : 2
source     :
    - https://download.gnome.org/sources/gnome-recipes/1.6/gnome-recipes-1.6.2.tar.xz : 8a11ed483b422dbbedb10237dac8b47fe94d76d40cac87ae6d19292942c94f9c
license    : GPL-3.0
component  : desktop.gnome
summary    : An easy-to-use application that will help you to discover what to cook today, tomorrow, the rest of the week and for your special occasions.
description: |
    An easy-to-use application that will help you to discover what to cook today, tomorrow, the rest of the week and for your special occasions.
builddeps  :
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gspell-1)
    - pkgconfig(libcanberra)
    - pkgconfig(libsoup-2.4)
    - git
    - itstool
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
